@tokens = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlcjIiLCJleHAiOjE2NTQ2NjA4Mjh9.DJBy86V3g5Ya6DrNNABrAHLgwPlB7djxfoFfBihcUR8

### USER SERVICE
### ADD USER
POST https://fazztrack-vehicle.herokuapp.com/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "oman",
    "email": "oman@mail.com",
    "password": "password"
}

### FIND USERS
GET https://fazztrack-vehicle.herokuapp.com/users/search?name=indras HTTP/1.1
Content-Type: application/json

### SORT USERS
GET https://fazztrack-vehicle.herokuapp.com/users/sort?sort=desc HTTP/1.1
Content-Type: application/json

### GET USERS
GET https://fazztrack-vehicle.herokuapp.com/users/ HTTP/1.1
Content-Type: application/json

### GET USER
GET https://fazztrack-vehicle.herokuapp.com/users/2 HTTP/1.1
Content-Type: application/json

### UPDATE USER
PUT https://fazztrack-vehicle.herokuapp.com/users/2 HTTP/1.1
Content-Type: application/json

{
    "name": "budi",
    "email": "budi@mail.com",
    "password": "budi"
}

### DELETE USER
DELETE https://fazztrack-vehicle.herokuapp.com/users/2 HTTP/1.1
Content-Type: application/json

### VEHICLE_TYPES SERVICE
### ADD VEHICLE_TYPES
POST https://fazztrack-vehicle.herokuapp.com/vehicles/types/ HTTP/1.1
Content-Type: application/json

{
    "name": "Motorcycle"
}

### FIND VEHICLE_TYPES
GET https://fazztrack-vehicle.herokuapp.com/vehicles/types/search?name=Car HTTP/1.1
Content-Type: application/json

### SORT VEHICLE_TYPES
GET https://fazztrack-vehicle.herokuapp.com/vehicles/types/sort?sort=desc HTTP/1.1
Content-Type: application/json

### GET VEHICLE_TYPES
GET https://fazztrack-vehicle.herokuapp.com/vehicles/types/ HTTP/1.1
Content-Type: application/json

### GET VEHICLE_TYPE
GET https://fazztrack-vehicle.herokuapp.com/vehicles/types/2 HTTP/1.1
Content-Type: application/json

### UPDATE VEHICLE_TYPE
PUT https://fazztrack-vehicle.herokuapp.com/vehicles/types/3 HTTP/1.1
Content-Type: application/json

{
    "name": "Dummy"
}

### DELETE VEHICLE_TYPE
DELETE https://fazztrack-vehicle.herokuapp.com/vehicles/types/3 HTTP/1.1
Content-Type: application/json

### VEHICLE SERVICE
### ADD VEHICLE
POST https://fazztrack-vehicle.herokuapp.com/vehicles/ HTTP/1.1
Content-Type: application/json

{
    "vehicle_type_id": 2,
    "name": "Ferrari",
    "image": "https://images.unsplash.com/photo-1566008885218-90abf9200ddb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3264&q=80",
    "book_count": 1,
    "is_highlight": 0,
    "stock": 5,
    "price": 2000,
    "alternative_price": 200
}

### FIND VEHICLES
GET https://fazztrack-vehicle.herokuapp.com/vehicles/search?is_highlight=1 HTTP/1.1
Content-Type: application/json

### SORT VEHICLES
GET https://fazztrack-vehicle.herokuapp.com/vehicles/sort?sort=desc HTTP/1.1
Content-Type: application/json

### GET VEHICLES
GET https://fazztrack-vehicle.herokuapp.com/vehicles/ HTTP/1.1
Content-Type: application/json

### GET VEHICLE
GET https://fazztrack-vehicle.herokuapp.com/vehicles/1 HTTP/1.1
Content-Type: application/json

### UPDATE VEHICLE
PUT https://fazztrack-vehicle.herokuapp.com/vehicles/1 HTTP/1.1
Content-Type: application/json

{
    "vehicle_type_id": 1,
    "name": "Brio",
    "image": "https://images.unsplash.com/photo-1566008885218-90abf9200ddb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3264&q=80",
    "book_count": 1,
    "is_highlight": 1,
    "stock": 5,
    "price": 2000,
    "alternative_price": 200
}

### DELETE VEHICLE
DELETE https://fazztrack-vehicle.herokuapp.com/vehicles/13 HTTP/1.1
Content-Type: application/json

### ORDER SERVICE
### ADD ORDER
POST https://fazztrack-vehicle.herokuapp.com/orders/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "vehicle_id": 5,
    "order_code": "C0001",
    "status": 0,
    "qty": 5,
    "order_date": 2022-06-13 03:04:30.076 +0700,
    "return_date": 2022-06-12 03:04:30.076 +0700
}

### FIND ORDERS
GET https://fazztrack-vehicle.herokuapp.com/orders/order_date=time HTTP/1.1
Content-Type: application/json

### SORT ORDERS
GET https://fazztrack-vehicle.herokuapp.com/orders/sort?sort=desc HTTP/1.1
Content-Type: application/json

### GET ORDERS
GET https://fazztrack-vehicle.herokuapp.com/orders/ HTTP/1.1
Content-Type: application/json

### GET ORDER
GET https://fazztrack-vehicle.herokuapp.com/orders/12 HTTP/1.1
Content-Type: application/json

### UPDATE ORDER
PUT https://fazztrack-vehicle.herokuapp.com/orders/12 HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "vehicle_id": 0,
    "order_code": "1",
    "status": 0,
    "qty": 5,
    "order_date": 2022-06-13 03:04:30.076 +0700,
    "return_date": 2022-06-12 03:04:30.076 +0700
}

### DELETE ORDER
DELETE https://fazztrack-vehicle.herokuapp.com/orders/13 HTTP/1.1
Content-Type: application/json

### FAVORITE SERVICE
### ADD FAVORITE
POST https://fazztrack-vehicle.herokuapp.com/favorites/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 2,
    "vehicle_id":2
}

### FIND FAVORITES
GET https://fazztrack-vehicle.herokuapp.com/favorites/FAVORITE_date=time HTTP/1.1
Content-Type: application/json

### SORT FAVORITES
GET https://fazztrack-vehicle.herokuapp.com/favorites/sort?sort=desc HTTP/1.1
Content-Type: application/json

### GET FAVORITES
GET https://fazztrack-vehicle.herokuapp.com/favorites/ HTTP/1.1
Content-Type: application/json

### GET FAVORITE
GET https://fazztrack-vehicle.herokuapp.com/favorites/1 HTTP/1.1
Content-Type: application/json

### UPDATE FAVORITE
PUT https://fazztrack-vehicle.herokuapp.com/favorites/2 HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "vehicle_id": 1
}

### DELETE FAVORITE
DELETE https://fazztrack-vehicle.herokuapp.com/favorites/13 HTTP/1.1
Content-Type: application/json

### AUTH LOGIN
POST https://fazztrack-vehicle.herokuapp.com/auth/ HTTP/1.1
Content-Type: application/json

{
    "name": "alip",
    "password": "password"
}
